name: Release firmata-controlpanel

on:
  push:
    tags:
      - 'v*.*.*'
      - 'v*.*.*-alpha*'
      - 'v*.*.*-beta*'
      - 'v*.*.*-rc*'

jobs:
  build_mac:
    runs-on: macos-13
    env:
      BUILD_MAC: false
      BUILD_WINDOWS: true
      BUILD_RASPBERRY: true
      BUILD_LINUX: true

    steps:
    - name: Checkout code
      if: ${{ env.BUILD_MAC == 'true' }}
      uses: actions/checkout@v4

    - name: Set up Go
      if: ${{ env.BUILD_MAC == 'true' }}
      uses: actions/setup-go@v2
      with:
        go-version: '1.23.4'

    - name: Install gh CLI
      if: ${{ env.BUILD_MAC == 'true' }}
      run: |
        brew install gh

    - name: Extract tag
      id: extract_tag
      run: |
        echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

    - name: Substitute tag in config.go
      if: ${{ env.BUILD_MAC == 'true' }}
      run: |
        # use this approach because we can't easily set ldflags in fyne-cross
        sed -i '' "s/_TAG_/${TAG}/g" config.go

    - name: Install fyne
      if: ${{ env.BUILD_MAC == 'true' }}
      run: go install fyne.io/fyne/v2/cmd/fyne@latest

    - name: Install appdmg
      if: ${{ env.BUILD_MAC == 'true' }}
      run: npm install -g appdmg

    # - name: Build for macOS arm64
    #   if: ${{ env.BUILD_MAC == 'true' }}
    #   run: |
    #     export GOOS=darwin
    #     export GOARCH=arm64
    #     export CGO_ENABLED=1
    #     go build -o firmata .

    # - name: Package for macOS arm64
    #   if: ${{ env.BUILD_MAC == 'true' }}
    #   run: |
    #     export GOOS=darwin
    #     export GOARCH=arm64
    #     export CGO_ENABLED=1
    #     rm -rf firmata.app
    #     fyne package -os darwin -icon Icon.png -name firmata -executable firmata

    # - name: Move macOS arm64 app to dist directory
    #   if: ${{ env.BUILD_MAC == 'true' }}
    #   run: |
    #     rm -rf dist/darwin-arm64
    #     mkdir -p dist/darwin-arm64
    #     mv firmata.app dist/darwin-arm64/
    #     ls -l dist/darwin-arm64

    # - name: Create DMG for macOS arm64
    #   if: ${{ env.BUILD_MAC == 'true' }}
    #   run: |
    #     mkdir -p artifacts
    #     appdmg dist/appdmg_arm64.json artifacts/macOS_Apple_M-series_Control_Panel_Installer.dmg

    - name: Build for macOS amd64
      if: ${{ env.BUILD_MAC == 'true' }}
      run: |
        rm -f firmata
        export GOOS=darwin
        export GOARCH=amd64
        export CGO_ENABLED=1
        go build -o firmata .

    - name: Package for macOS amd64
      if: ${{ env.BUILD_MAC == 'true' }}
      run: |
        rm -rf firmata.app
        fyne package -os darwin -icon Icon.png -name firmata -executable firmata

    - name: Move macOS amd64 app to dist directory
      if: ${{ env.BUILD_MAC == 'true' }}
      run: |
        rm -rf dist/darwin-amd64
        mkdir -p dist/darwin-amd64
        mv firmata.app dist/darwin-amd64/

    - name: Create DMG for macOS amd64
      if: ${{ env.BUILD_MAC == 'true' }}
      run: |
        mkdir -p artifacts
        appdmg dist/appdmg_amd64.json artifacts/macOS_Control_Panel_Installer.dmg

    - name: Upload macOS amd64 DMG
      if: ${{ env.BUILD_MAC == 'true' }}
      uses: actions/upload-artifact@v4
      with:
        name: build_mac_artifacts
        path: artifacts/*

  build_crosscompile:
    runs-on: ubuntu-latest
    env:
      BUILD_MAC: false
      BUILD_WINDOWS: true
      BUILD_RASPBERRY: true
      BUILD_LINUX: true

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install GitHub CLI
      run: |
        wget https://github.com/cli/cli/releases/download/v2.32.0/gh_2.32.0_linux_amd64.deb
        sudo dpkg -i gh_2.32.0_linux_amd64.deb

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.23.4'

    - name: Install fyne-cross
      run: |
        go install github.com/fyne-io/fyne-cross@latest
        echo "${HOME}/go/bin" >> $GITHUB_PATH

    - name: Extract tag
      id: extract_tag
      run: |
        echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
        echo "DEB_TAG=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

    - name: Substitute tag in config.go
      run: |
        sed -i "s/_TAG_/${TAG}/g" config.go

    # Windows build steps
    - name: Build for Windows
      if: ${{ env.BUILD_WINDOWS == 'true' }}
      run: |
        fyne-cross windows -arch amd64 -app-id app.owlcms.firmata-launcher -name firmata -debug
        mkdir -p artifacts
        mv fyne-cross/bin/windows-amd64/firmata.exe artifacts/firmata.exe

    # Linux and Raspberry Pi preparation
    - name: Install Ruby
      if: ${{ env.BUILD_LINUX == 'true' }}
      run: sudo apt-get install -y ruby-full

    - name: Install fpm
      if: ${{ env.BUILD_LINUX == 'true' }}
      run: |
        sudo gem install --no-document fpm
        echo "$(gem environment gemdir)/bin" >> $GITHUB_PATH

    # Linux Intel steps
    - name: Build for Linux amd64
      if: ${{ env.BUILD_LINUX == 'true' }}
      run: fyne-cross linux -arch amd64 -app-id app.owlcms.firmata-launcher -icon Icon.png -name firmata

    - name: Copy Linux binary
      if: ${{ env.BUILD_LINUX == 'true' }}
      run: cp fyne-cross/bin/linux-amd64/firmata-launcher fyne-cross/bin/linux-amd64/firmata-linux

    - name: Create Linux Intel DEB package
      if: ${{ env.BUILD_LINUX == 'true' }}
      run: |
        cd ./fyne-cross/dist/linux-amd64
        tar -xf firmata.tar.xz
        rm -f firmata.tar.xz Makefile
        fpm -s dir -t deb -n firmata-launcher -v ${DEB_TAG} -a amd64 --prefix / \
          --deb-no-default-config-files \
          --after-install ../../../dist/after_install.sh \
          --after-remove ../../../dist/after_remove.sh \
          .
        cd -
        mkdir -p artifacts
        mv ./fyne-cross/dist/linux-amd64/firmata-launcher_${DEB_TAG}_amd64.deb artifacts/Linux_Control_Panel_Installer.deb
        sh +x

    # Raspberry Pi steps
    - name: Build for Linux arm64
      if: ${{ env.BUILD_RASPBERRY == 'true' }}
      run: fyne-cross linux -arch arm64 -app-id app.owlcms.firmata-launcher -icon Icon.png -name firmata

    - name: Copy Raspberry Pi binary
      if: ${{ env.BUILD_RASPBERRY == 'true' }}
      run: cp fyne-cross/bin/linux-arm64/firmata-launcher fyne-cross/bin/linux-arm64/firmata-pi

    - name: Create Raspberry Pi DEB package
      if: ${{ env.BUILD_RASPBERRY == 'true' }}
      run: |
        cd ./fyne-cross/dist/linux-arm64/
        tar -xf firmata.tar.xz
        rm -f firmata.tar.xz Makefile
        fpm -s dir -t deb -n firmata-launcher -v ${DEB_TAG} -a arm64 --prefix / \
          --deb-no-default-config-files \
          --after-install ../../../dist/after_install.sh \
          --after-remove ../../../dist/after_remove.sh \
          .
        cd -
        mkdir -p artifacts
        mv ./fyne-cross/dist/linux-arm64/firmata-launcher_${DEB_TAG}_arm64.deb artifacts/Raspberry_Pi_arm64_Control_Panel_Installer.deb

    # Save artifacts for later steps
    - name: Upload build_crosscompile_artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build_crosscompile_artifacts
        path: artifacts/*

  package_windows:
    runs-on: windows-latest
    needs: build_crosscompile
    env:
      BUILD_MAC: false
      BUILD_WINDOWS: true
      BUILD_RASPBERRY: true
      BUILD_LINUX: true

    steps:
    - name: Checkout code
      if: ${{ env.BUILD_WINDOWS == 'true' }}
      uses: actions/checkout@v4

    - name: Extract tag
      id: extract_tag
      run: |
        echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
        echo "DEB_TAG=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

    - name: Install gh CLI
      if: ${{ env.BUILD_WINDOWS == 'true' }}
      run: choco install gh

    - name: Download build_crosscompile_artifacts
      if: ${{ env.BUILD_WINDOWS == 'true' }}
      uses: actions/download-artifact@v4
      with:
        name: build_crosscompile_artifacts
        path: ./dist

    - name: Prepare Inno Setup directory
      if: ${{ env.BUILD_WINDOWS == 'true' }}
      run: |
        mkdir dist/iss
        cp dist/firmata.exe dist/iss/
        cp dist/*.ico dist/iss/

    - name: Install Inno Setup
      if: ${{ env.BUILD_WINDOWS == 'true' }}
      run: choco install innosetup

    - name: Run Inno Setup
      if: ${{ env.BUILD_WINDOWS == 'true' }}
      run: |
        cd dist
        & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" "setup.iss"
        dir
        cd ..
        mkdir artifacts
        mv dist\firmata-Panel-installer_windows.exe artifacts\Windows_Control_Panel_Installer.exe
        cp dist\firmata.exe artifacts\firmata_controlpanel.exe

    - name: Install MSIX Packaging Tools
      if: ${{ env.BUILD_WINDOWS == 'true' }}
      run: |
        choco install msix -y

    - name: Create MSIX Package
      if: ${{ env.BUILD_WINDOWS == 'true' }}
      run: |
        mkdir dist\msix
        cp dist\firmata.exe dist\msix\
        cp -r dist\Assets dist\msix\
        # Update version in manifest
        $manifestContent = Get-Content dist\AppxManifest.xml -Raw
        $manifestContent = $manifestContent -replace '_TAG_',$env:TAG.TrimStart('v')
        $manifestContent | Set-Content dist\msix\AppxManifest.xml -Force
        MakeAppx pack /d dist\msix /p artifacts\firmata-Panel_windows_${{ env.TAG }}.msix /f AppxManifest.xml
        # Self-sign the package for testing
        New-SelfSignedCertificate -Type Custom -Subject "CN=OWLCMSDev, O=OWLCMS, C=CA" -KeyUsage DigitalSignature -FriendlyName "OWLCMS Development Certificate" -CertStoreLocation "Cert:\CurrentUser\My" -TextExtension @("2.5.29.37={text}1.3.6.1.5.5.7.3.3", "2.5.29.19={text}")
        $cert = (Get-ChildItem Cert:\CurrentUser\My | Where-Object {$_.FriendlyName -eq "OWLCMS Development Certificate"})
        SignTool sign /fd SHA256 /a /f $cert artifacts\firmata-Panel_windows_${{ env.TAG }}.msix

    - name: Save package_windows_artifacts
      if: ${{ env.BUILD_WINDOWS == 'true' }}
      uses: actions/upload-artifact@v4
      with:
        name: package_windows_artifacts
        path: artifacts/*

  create_release:
    runs-on: ubuntu-latest
    needs: [build_mac, build_crosscompile, package_windows]
    env:
      BUILD_MAC: false
      BUILD_WINDOWS: true
      BUILD_RASPBERRY: true
      BUILD_LINUX: true

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Extract tag
      id: extract_tag
      run: |
        echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
        echo "DEB_TAG=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

    - name: Create dist directory
      run: mkdir -p dist

    - name: Prepare release notes
      run: |
        cp RELEASE.md ./dist/RELEASE.md
        sed -i "s/_TAG_/${TAG}/g" ./dist/RELEASE.md

    # one single download for each of the job needs, in the same order
    - name: Download build_mac_artifacts
      if: ${{ env.BUILD_MAC == 'true' }}
      uses: actions/download-artifact@v4
      with:
        name: build_mac_artifacts
        path: ./dist

    - name: Download build_crosscompile_artifacts
      if: ${{ env.BUILD_RASPBERRY == 'true' || env.BUILD_LINUX == 'true' }}
      uses: actions/download-artifact@v4
      with:
        name: build_crosscompile_artifacts
        path: ./dist

    - name: Download package_windows_artifacts
      if: ${{ env.BUILD_WINDOWS == 'true' }}
      uses: actions/download-artifact@v4
      with:
        name: package_windows_artifacts
        path: ./dist

    - name: Create GitHub Release
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      shell: bash
      run: |
        if [[ "${TAG}" == *"-"* ]]; then
          gh release create ${{ env.TAG }} \
            --title "firmata Control Panel ${{ env.TAG }}" \
            --notes-file ./dist/RELEASE.md \
            --prerelease
        else
          gh release create ${{ env.TAG }} \
            --title "firmata Control Panel ${{ env.TAG }}" \
            --notes-file ./dist/RELEASE.md
        fi

    # - name: Release macOS arm64 DMG
    #   if: ${{ env.BUILD_MAC == 'true' }}
    #   env:
    #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   run: |
    #     gh release upload ${{ env.TAG }} dist/macOS_Apple_M-series_Control_Panel_Installer.dmg

    - name: Release macOS amd64 DMG
      if: ${{ env.BUILD_MAC == 'true' }}
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release upload ${{ env.TAG }} dist/macOS_Control_Panel_Installer.dmg

    - name: Release Raspberry Pi DEB package
      if: ${{ env.BUILD_RASPBERRY == 'true' }}
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release upload ${{ env.TAG }} dist/Raspberry_Pi_arm64_Control_Panel_Installer.deb

    - name: Release Linux Intel DEB package
      if: ${{ env.BUILD_LINUX == 'true' }}
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release upload ${{ env.TAG }} dist/Linux_Control_Panel_Installer.deb

    - name: Release Windows installer
      if: ${{ env.BUILD_WINDOWS == 'true' }}
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release upload ${{ env.TAG }} dist/Windows_Control_Panel_Installer.exe

    - name: Release Windows Executable
      if: ${{ env.BUILD_WINDOWS == 'true' }}
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release upload ${{ env.TAG }} dist/firmata_controlpanel.exe

    - name: Release Windows MSIX package
      if: ${{ env.BUILD_WINDOWS == 'true' }}
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release upload ${{ env.TAG }} dist/firmata-Panel_windows_${{ env.TAG }}.msix

